Raw Attributes
xmidt-org/talaria pull request #162
Opened 2020-12-03 18:34 UTC by j-mai

This PR allows for talaria to get all of a JWT's claims from an Attribute parsed using bascule.

2020-12-04 17:49 UTC, kcajmagic requested changes
looks good, just a couple of minor changes.

2020-12-04 17:49 UTC, kcajmagic commented on middleware.go
> +				metadata.SetClaims(auth.Token.Attributes().(rawAttributes).GetRawAttributes())
We should add a check to see if it is a `RawAttributes`

```suggestion
				if tokenAttributes, ok := auth.Token.Attributes().(RawAttributes); ok {
					metadata.SetClaims(tokenAttributes.GetRawAttributes())
				}
```

2020-12-04 17:49 UTC, kcajmagic commented on mocks_test.go
> +	arguments := parser.Called(token)
all parameters should be passed in mock struct
```suggestion
	arguments := parser.Called(token, claims, parseFunc)
```

2020-12-04 17:49 UTC, kcajmagic commented on tokenFactory_test.go
> +
```suggestion
```

2020-12-04 17:49 UTC, kcajmagic commented on tokenFactory_test.go
> +
```suggestion
```

2020-12-04 17:49 UTC, kcajmagic commented on tokenFactory_test.go
> +
```suggestion
```

2020-12-07 21:31 UTC, kcajmagic approved these changes
Awesome, looks good.

2020-12-08 04:06 UTC, kristinaspring reviewed
Just one question - not sure about the desired middleware functionality.

2020-12-08 19:59 UTC, kristinaspring approved these changes
looks good 💯

2020-12-08 20:02 UTC, merged