disable sat token checks for docker
xmidt-org/talaria pull request #297
Opened 2023-03-03 22:33 UTC by piccione99

remove sat token checks from the docker config since we are using basic auth for the local environment.

2023-03-03 22:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/xmidt-org/talaria?pullRequest=297) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/xmidt-org/talaria?pullRequest=297) before we can accept your contribution.<br/><hr/>**Marcia Piccione** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/xmidt-org/talaria?pullRequest=297) it.</sub>

2023-03-04 00:39 UTC, schmidtw approved these changes

2023-03-06 16:54 UTC, denopink requested changes
u forgot to update the bottom section of the changelog
```markdown
[Unreleased]: https://github.com/xmidt-org/talaria/compare/v0.6.10...HEAD
[v0.6.10]: https://github.com/xmidt-org/talaria/compare/v0.6.9...v0.6.10
```

2023-03-06 18:02 UTC, schmidtw approved these changes

2023-03-06 18:04 UTC, denopink approved these changes

2023-03-06 18:05 UTC, merged